package klite.sample.klite.jdbc

import ch.tutteli.atrium.api.fluent.en_GB.toEqual
import ch.tutteli.atrium.api.verbs.expect
import com.sun.net.httpserver.Headers
import io.mockk.every
import io.mockk.mockk
import klite.HttpExchange
import klite.OriginalHttpExchange
import klite.RouterConfig
import klite.jdbc.*
import klite.sample.DBTest
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import users.User
import java.sql.Connection
import java.sql.PreparedStatement
import java.util.*
import javax.sql.DataSource

/**
 * Shows how an app can load the session and the authenticated user in a single roundtrip, instead of the two queries
 * that [klite.jdbc.DBSessionStore.load] followed by `userRepository.get(userId)` would need.
 *
 * The store has to run the join itself, because [HttpExchange.session] is always loaded by the framework (when the
 * response is started), so a separate user query is a second roundtrip.
 */
class DBSessionStoreJoinTest: DBTest() {
  abstract class MockableExchange: OriginalHttpExchange()

  val requestHeaders = Headers()
  val responseHeaders = Headers()

  /** counts prepared statements, to prove that the session and the user really come from one roundtrip */
  val statements = mutableListOf<String>()
  val countingDb = object: DataSource by db {
    override fun getConnection(): Connection {
      val conn = db.connection
      return object: Connection by conn {
        override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
          conn.prepareStatement(sql, autoGeneratedKeys).also { statements += sql }
      }
    }
  }

  /** the app's own DataSource has to be kept, as DBSessionStore does not expose its own */
  class JoinedSessionStore(db: DataSource, table: String): DBSessionStore(db, table) {
    override fun load(id: UUID, exchange: HttpExchange): MutableMap<String, String?>? {
      return db.query("select s.params, u.* from $table s left join users u on u.id::text = s.params->>'userId'", listOf("s.id" to id)) {
        exchange.attrPut(create<User>())
        getJson<MutableMap<String, String?>>("params").toMutableMap()
      }.firstOrNull()
    }
  }

  @BeforeEach fun createTable() = ChangeSetFileReader("migrator/db_sessions.sql").forEach { changeSet ->
    changeSet.statements.forEach { countingDb.exec(it) }
  }

  @Test fun `session attributes and the user are loaded in one statement`() {
    val store = JoinedSessionStore(countingDb, "db_sessions")
    val session = store.load(newExchange())
    session["userId"] = "9725b054-426b-11ee-92a5-0bd2a151eea2" // the test user of sample/db/users.sql
    store.save(newExchange(), session)

    statements.clear()
    val exchange = newExchange(cookie = savedCookieValue!!)
    val loaded = store.load(exchange)

    expect(loaded.isNew).toEqual(false)
    expect(loaded["userId"]).toEqual("9725b054-426b-11ee-92a5-0bd2a151eea2")
    expect(exchange.attr<User>().email.value).toEqual("test@codeborne.com")
    expect(statements.size).toEqual(1)
  }

  private val savedCookieValue get() = responseHeaders["Set-Cookie"]?.single()?.substringAfter("S=")?.substringBefore(';')

  private fun newExchange(cookie: String? = null): HttpExchange {
    requestHeaders.clear()
    responseHeaders.clear()
    cookie?.let { requestHeaders.add("Cookie", "S=$it") }
    val original = mockk<MockableExchange>(relaxed = true) {
      every { requestMethod } returns "GET"
      every { responseCode } returns -1
      every { requestHeaders } returns this@DBSessionStoreJoinTest.requestHeaders
      every { responseHeaders } returns this@DBSessionStoreJoinTest.responseHeaders
    }
    return HttpExchange(original, mockk<RouterConfig>(relaxed = true), null, "req-id")
  }
}
